### ISSUE TITLE
Use java instead of / in addition to smali

### ISSUE THREAD

**Issue by Vendicated** [Wumpus-Central/Discord-Datamining-Android#3]
smali is hard to understand and considering you don't include library smali files, the smali files are not re-compilable anyway

Using [jadx](https://github.com/skylot/jadx) (you might want to use [Aliucord's jadx](https://github.com/Aliucord/jadx) to remove the very noisy kotlin metadata annotations), you can easily decompile dex files into very readable java files

See https://gitdab.com/Juby210/discord-jadx for an example output

**Comment by DzikStar** [comment]
Hey, that's a really great idea. Thank you for your suggestion. I'll implement it later.

By the way, do you think it will be better to use JADX version 1.4.7 from the official repository or version 1.3.2 from aliucord release? I don't know whether to consider compiling a new version from aliucord, I've never dealt with it before

**Comment by DzikStar** [comment]
## Suggestion accepted. 
Everything was successfully implemented after solving the first small problems
